[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vindy"
version = "1.0.1"
authors = [
  { name="Jonas Kneifl", email="jonas@kneifl.eu" },
  { name="Paolo Conti", email="paolo.conti@polimi.it" },
]
description = "AESINDy is a Python package for automated system identification of low-dimensional systems combining autoencoders and SINDy."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.8",
    "numpy>=1.26",
    "scikit_learn>=1.2",
    "scipy>=1.13",
    "sympy>=1.12",
    "torch>=2.0",
    "imageio>=2.30",
]
keywords = [
    "model order reduction",
    "system identification",
    "surrogate modeling",
    "reduced order models",
    "variational",
    "uncertainty quantification",
    "generative modeling",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
gui = [
    "visualizer-3d",
]
interfaces = [
]
test = [
    "pytest>=7.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
#package-data = {"sample" = ["*.dat"]}

[project.urls]
Homepage = "https://github.com/jkneifl/VENI-VINDy-VICI"
Issues = "https://github.com/jkneifl/VENI-VINDy-VICI/issues"